# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.regular_account_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.regular_account_button.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.regular_account_button.setObjectName("regular_account_button")
        self.saving_account_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saving_account_button.setGeometry(QtCore.QRect(180, 10, 101, 23))
        self.saving_account_button.setObjectName("saving_account_button")
        self.balance_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.balance_label.setGeometry(QtCore.QRect(20, 50, 251, 16))
        self.balance_label.setObjectName("balance_label")
        self.user_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_entry.setGeometry(QtCore.QRect(20, 80, 251, 20))
        self.user_entry.setObjectName("user_entry")
        self.set_balance_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.set_balance_button.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.set_balance_button.setObjectName("set_balance_button")
        self.deposit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deposit_button.setGeometry(QtCore.QRect(110, 120, 75, 23))
        self.deposit_button.setObjectName("deposit_button")
        self.withdraw_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.withdraw_button.setGeometry(QtCore.QRect(200, 120, 75, 23))
        self.withdraw_button.setObjectName("withdraw_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "accounts"))
        self.regular_account_button.setText(_translate("MainWindow", "Regular account"))
        self.saving_account_button.setText(_translate("MainWindow", "Savings Account"))
        self.balance_label.setText(_translate("MainWindow", "Balance"))
        self.set_balance_button.setText(_translate("MainWindow", "Set Balance"))
        self.deposit_button.setText(_translate("MainWindow", "Deposit"))
        self.withdraw_button.setText(_translate("MainWindow", "Withdraw"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
